# Generated by Django 4.0.10 on 2024-08-25 19:18

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('maxScore', models.IntegerField()),
                ('instructions', models.TextField()),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('progressive', 'Progressive'), ('standard', 'Standard'), ('highscore', 'Highscore'), ('layout', 'Layout'), ('attempt', 'Attempt')], max_length=255)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('layouts', models.IntegerField(blank=True, null=True)),
                ('layoutMaxScore', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('maxScore', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DrillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_sets', to=settings.AUTH_USER_MODEL)),
                ('drills', models.ManyToManyField(related_name='drill_sets', to='core.drill')),
            ],
        ),
        migrations.CreateModel(
            name='TableSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drillName', models.CharField(max_length=255)),
                ('ballPositionProps', models.JSONField(blank=True, null=True)),
                ('pottingPocketProp', models.JSONField(blank=True, null=True)),
                ('targetSpecs', models.JSONField(blank=True, null=True)),
                ('leaveLineProp', models.JSONField(blank=True, null=True)),
                ('kickShotLineProp', models.JSONField(blank=True, null=True)),
                ('bankShotLineProp', models.JSONField(blank=True, null=True)),
                ('startIndex', models.IntegerField()),
                ('showShotLine', models.BooleanField()),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_setups', to='core.drill')),
            ],
        ),
        migrations.CreateModel(
            name='DrillSetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_scores', to='core.drillset')),
                ('scores', models.ManyToManyField(related_name='drill_set_scores', to='core.drillscore')),
                ('user', models.ForeignKey(default=core.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='drill_set_scores_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='drill',
            name='tableSetup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drill_table_setup', to='core.tablesetup'),
        ),
    ]
