# Generated by Django 4.0.10 on 2024-08-27 20:54

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillset',
            name='createdBy',
            field=models.ForeignKey(default=core.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='drill_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DrillSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drill')),
                ('drill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drillset')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
