# Generated by Django 4.0.10 on 2024-08-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_drillset_createdby_drillsetmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillscore',
            name='isSet',
            field=models.BooleanField(default=False),
        ),
    ]
