# Generated by Django 4.0.10 on 2024-07-15 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_drillscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillscore',
            name='date',
        ),
        migrations.AddField(
            model_name='drillscore',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
