# Generated by Django 4.0.10 on 2024-08-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_drillscore_date_drillscore_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maxScore', models.IntegerField()),
                ('instructions', models.TextField()),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(choices=[('progressive', 'Progressive'), ('standard', 'Standard'), ('highscore', 'Highscore'), ('layout', 'Layout'), ('attempt', 'Attempt')], max_length=255)),
                ('skills', models.JSONField()),
                ('attempts', models.IntegerField(blank=True, null=True)),
                ('layouts', models.IntegerField(blank=True, null=True)),
                ('layoutMaxScore', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
