# Generated by Django 4.0.10 on 2024-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_drillscore_isset'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillsetscore',
            name='total_max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='drillsetscore',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
