# Generated by Django 4.0.10 on 2024-08-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drillsetscore_total_max_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillsetscore',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
