# Generated by Django 4.0.10 on 2024-08-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_drill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drill',
            name='layoutMaxScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
