# Generated by Django 4.0.10 on 2024-08-10 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_drill_layoutmaxscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='uploadedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
