# Generated by Django 4.0.10 on 2024-08-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_drill_uploadedby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='drill',
            name='skills',
        ),
        migrations.AddField(
            model_name='drill',
            name='skills',
            field=models.ManyToManyField(to='core.skill'),
        ),
    ]
