# Generated by Django 4.0.10 on 2024-08-11 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_skill_remove_drill_skills_drill_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drill',
            name='skills',
        ),
        migrations.AddField(
            model_name='drill',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drillscore',
            name='drillId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.drill'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
