# Generated by Django 4.0.10 on 2024-08-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_drill_skills_drill_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillscore',
            old_name='drillId',
            new_name='drill',
        ),
    ]
