# Generated by Django 4.0.10 on 2024-08-12 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_drillid_drillscore_drill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillscore',
            name='drill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.drill'),
        ),
    ]
