# Generated by Django 4.0.10 on 2024-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_drillscore_drill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillscore',
            name='drill',
            field=models.IntegerField(),
        ),
    ]
