# Generated by Django 4.0.10 on 2024-08-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_drillscore_drill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillscore',
            old_name='drill',
            new_name='drillId',
        ),
    ]
