# Generated by Django 4.0.10 on 2024-08-12 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_drill_drillscore_drillid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drillscore',
            name='drillId',
        ),
        migrations.AddField(
            model_name='drillscore',
            name='drill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.drill'),
            preserve_default=False,
        ),
    ]
