# Generated by Django 4.0.10 on 2024-08-13 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_drillscore_drillid_drillscore_drill'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_sets', to=settings.AUTH_USER_MODEL)),
                ('drills', models.ManyToManyField(related_name='drill_sets', to='core.drill')),
            ],
        ),
    ]
