# Generated by Django 4.0.10 on 2024-08-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_drillset'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillSetScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_scores', to='core.drillset')),
                ('scores', models.ManyToManyField(related_name='drill_set_scores', to='core.drillscore')),
            ],
        ),
    ]
