# Generated by Django 4.0.10 on 2024-08-15 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_drillsetscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='drillsetscore',
            name='createdBy',
            field=models.ForeignKey(default=888, on_delete=django.db.models.deletion.CASCADE, related_name='drill_set_scores_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
