# Generated by Django 4.0.10 on 2024-08-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_drillsetscore_createdby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drillsetscore',
            old_name='createdBy',
            new_name='user',
        ),
    ]
