# Generated by Django 4.0.10 on 2024-08-15 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_createdby_drillsetscore_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drill',
            old_name='uploadedBy',
            new_name='createdBy',
        ),
    ]
