# Generated by Django 4.0.10 on 2024-08-15 19:02

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_uploadedby_drill_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drillsetscore',
            name='user',
            field=models.ForeignKey(default=core.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='drill_set_scores_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
