# Generated by Django 4.0.10 on 2024-08-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_drillsetscore_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballPositionProps', models.JSONField(blank=True, null=True)),
                ('pottingPocketProp', models.JSONField(blank=True, null=True)),
                ('targetSpecs', models.JSONField(blank=True, null=True)),
                ('leaveLineProp', models.JSONField(blank=True, null=True)),
                ('kickShotLineProp', models.JSONField(blank=True, null=True)),
                ('bankShotLineProp', models.JSONField(blank=True, null=True)),
                ('startIndex', models.IntegerField()),
                ('showShotLine', models.BooleanField()),
                ('drill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_setup_detail', to='core.drill')),
            ],
        ),
        migrations.AddField(
            model_name='drill',
            name='tableSetup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drill_table_setup', to='core.tablesetup'),
        ),
    ]
