# Generated by Django 4.0.10 on 2024-08-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tablesetup_drill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesetup',
            name='drill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_setups', to='core.drill'),
        ),
    ]
